runtime: nodejs14

manual_scaling:
  instances: 1

resources:
  cpu: .5
  memory_gb: 0.5
  disk_size_gb: 10

# Change for production, no cache is used only for development
# Mitigates the problem where subsequent deployments from different machines won't work
default_expiration: 0

handlers:
  - url: /static
    static_dir: client/build/static
  - url: /(.*\.(json|ico|js))$
    static_files: client/build/\1
    upload: client/build/.*\.(json|ico|js)$
  - url: /
    static_files: client/build/index.html
    upload: client/build/index.html
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto
  